### ISSUE TITLE
The binary is big. please build a release build

### ISSUE THREAD

**Issue by liudonghua123** [MeshGeometry/cling-win#1]
Thanks for your work. I built cling according to https://root.cern.ch/cling-build-instructions , but failed with the error message on https://github.com/root-project/cling/issues/186#issuecomment-354407621 

And I hope someone else builds and shares a successful release build.

I download the repository, it is about 1.4G size, seems like a debug build compared to the linux/MacOS build on https://root.cern.ch/download/cling/

**Comment by danhambleton** [comment]
Nope, this is the release. The debug build is 14GB.
